### ISSUE TITLE
overwrite flag does not work

### ISSUE THREAD

**Issue by jkotan** [pni-libraries/python-pni#18]
Hi Eugen,

Testing my code I've just noticed  that the `overwrite` flag does not work, i.e.

    import pni.io.nx.h5 as nx
    nx.create_file("test.h5", True)
    nx.create_file("test.h5", True)

thows the following error:

    ---------------------------------------------------------------------------
    ObjectError                               Traceback (most recent call last)
    <ipython-input-8-a676b95b8e66> in <module>()
    ----> 1 nx.create_file("test.h5", True)
    
    /usr/lib/python2.7/dist-packages/pni/io/nx/h5/__init__.pyc in create_file(fname, overwrite)
         74     :raises :py:exc:`pni.core.FileError`: in case of problems
         75     """
    ---> 76     return __create_file(fname,overwrite)
         77 
         78 def create_files(fname,split_size,overwrite=False):
    
    ObjectError: Exception: object_error
    
    
    Description:
    HDF5 object ID < 0, object creation failed!
    
    Exception thrown by:
    /tmp/buildd/libpniio-1.1.0/src/nx/h5/object_imp.cpp	52	      pni::io::nx::h5::object_imp::object_imp(hid_t&&)

Cheers,
Jan

**Comment by jkotan** [comment]
Hi,

I've just realized the it does not work only if the file is not closed. If it is closed, i.e. 

    import pni.io.nx.h5 as nx
    fl = nx.create_file("test.h5", True)
    fl.close()
    nx.create_file("test.h5", True)


it works OK. 

So maybe  the above behavior is reasonable.

Cheers,
Jan

**Comment by eugenwintersberger** [comment]
This is not really intended behavior. I should investigate this. This works fine with C++. So I guess there is something wrong in the Python wrapper.

**Comment by eugenwintersberger** [comment]
Short update on this. There seems to be something odd with the garbage collector. If I put the file create function in a scope (function) it works.

If I do something like this it works

```python
def create():
    nx.create_file("test.nxs",True)

create()
create()
```
