### ISSUE TITLE
file close()  does no close all children

### ISSUE THREAD

**Issue by jkotan** [pni-libraries/python-pni#20]
Hi Eugen,

I've just found that  `nxfile.close()` does not close  all its children, i..e.

    import pni.io.nx.h5 as nx

    fl = nx.create_file("test.h5", True)
    root = fl.root()
    fl.close()
    fl = nx.create_file("test.h5", True)

throws  exception because the `root` object is not closed. 
I would expect that `nxfile.close()` closes all its children and the `root` object becomes invalid.
Then one could ask if `root.is_valid()` and  if not  reopen it.
That could be useful for the SWMR.

Unfortunetly, SWMR state cannot be switch dynamically, i.e. without closing all the file elements.

However, it could be easy to program it, e.g. inside  pni library,
On SWMR mode switch one could close all the file elements (without destroying the elements), switch the mode and reopen the file elements inside the same objects.
   
Cheers,
Jan

**Comment by eugenwintersberger** [comment]
Hi Jan. This is not a bug but simply the behavior of the HDF5 library. There is not garbage collection included ;). 

Even if I add something like a kind of garbage collection where all objects are destroyed when the file is closed I am not sure how this would help you with SWMR. You would have to reopen all required objects anyhow.

**Comment by jkotan** [comment]
Hi Eugen,

Ok. I thought it would be natural behavior that if you close  parent object all kids are close  as well. 
But if not, 
I will implement it in my writer.

Cheers,
Jan
