### ISSUE TITLE
Reading problems of groups with exotic names

### ISSUE THREAD

**Issue by jkotan** [pni-libraries/python-pni#23]
Hi Eugen,

I've just create a nexus file uning python-pni which has a name

    scan_2017-06-19T07:47:35.554207+0200

Unfortunatelty, when I try to read it

    import pni.io.nx.h5 as nexus

    root = nexus.open_file("testp04exp2_cp2.nxs").root()
    gr = root.open("scan_2017-06-19T07:47:35.554207+0200")

I get the following error:

    Traceback (most recent call last):
      File "readgroup.py", line 5, in <module>
        gr = f.open("scan_2017-06-19T07:47:35.554207+0200")
    pni.io.ParserError: Exception: parser_error
    
    
    Description:
    Error parsing string [testp04exp2_cp2.nxs://scan_2017-06-19T07:47:35.554207+0200] to nxpath!
    File section was:   [testp04exp2_cp2.nxs]
    Object section was: [/scan_2017-06-19T07:47:35.554207+0200]
    
    Exception thrown by:
    /tmp/buildd/libpniio-1.1.0/src/nx/nxpath/parser.cpp	75	pni::io::nx::nxpath pni::io::nx::parsers::parse_path(const string&)

I understand that this name may be not allowed by the NeXus Format standard, but in my opinion
if it  is possible to create any group in python-pni it should be also readable in python-pni.
Otherwise users may get confused: they think they store data and they have it but it is unreadable (at least from python-pni) .

Cheers,
Jan

**Comment by jkotan** [comment]
I looks like in the above case the problem comes from `:` ,  `.` and `+` characters. 
So would suggest 
either to make them acceptable in names 
or throw an exception during the group creation with not allowed characters.

**Comment by eugenwintersberger** [comment]
You are totally right. The above error comes from the :, ., and + characters which are not allowed in group and field names. See [here](http://download.nexusformat.org/doc/html/datarules.html) for a detailed description. In particular the colon sign would cause problems for the parser as it is used to separate group names and their type from each other. 

In so far the exception is correct. Though, I admit that error reporting in the currently released version of the library is bad. The new version got new parsers which should make error reporting easier. I still have to finish the Windows stuff until I can make a new release for Linux.

**Comment by jkotan** [comment]
But if the error is correct, I should get a similar error when I create a group with a wrong name.

**Comment by eugenwintersberger** [comment]
ok - fair enough that is a god point. Need to add a policy here. I will put the issue to the appropriate release milestone.
