### ISSUE TITLE
field shapes are not compatible with numpy shapes

### ISSUE THREAD

**Issue by jkotan** [pni-libraries/python-pni#3]
Hi Eugen,

I've noticed that field shapes are not compatible with numpy shapes.
In the previous version it was OK.

The following example which should run without errors:

    import numpy
    import pni.io.nx.h5 as nexus

    f = nexus.create_file("image_writer.nxs",True).root()
    nx = 1024
    ny = 2048

    shape1n = [1,ny]
    shapemn = [nx,ny]
    shapem1 = [nx,1]

    data1n = f.create_field("data1n","uint32",shape=shape1n, chunk=shape1n)
    datamn = f.create_field("datamn","uint32",shape=shapemn, chunk=shapemn)
    datam1 = f.create_field("datam1","uint32",shape=shapem1, chunk=shapem1)

    a1n = numpy.ones(shape=shape1n)
    amn = numpy.ones(shape=shapemn)
    am1 = numpy.ones(shape=shapem1)

    datamn[...] = amn
    # ERROR
    data1n[...] = a1n
    # ERROR
    datam1[...] = am1

Otherwise, user would have to check if any of dimensions is 1 

Cheers,
Jan

**Comment by eugenwintersberger** [comment]
A shorter version of the problem

```python
f = nexus.create_file(...)
r = f.root()
d = r.create_field("test","uint8",shape=(1,1024))
data = numpy.ones((1,1024))
d[...] = d

#this is where a shape mismatch error is thrown
```
