### ISSUE TITLE
regressions::issue_37 fails on jessie

### ISSUE THREAD

**Issue by jkotan** [pni-libraries/python-pni#43]
I've just noticed that on jessie:

          Start 22: regressions::issue_37
    *** Error in `/home/jkotan/sources/libpniio-build/bin/regression_issue_37': free(): invalid next size (fast): 0x00000000013a0610 ***
    *** Error in `/home/jkotan/sources/libpniio-build/bin/regression_issue_37': double free or corruption (!prev): 0x000000000139ae00 ***
    22/22 Test #22: regressions::issue_37 ....................***Exception: Other  0.01 sec

**Comment by eugenwintersberger** [comment]
Ok. Good to know. I will have a look at this sometime this week if this is ok.

**Comment by jkotan** [comment]
The ticket was moved to https://github.com/pni-libraries/libpniio/issues/92
