### ISSUE TITLE
 testBooleanArray on jessie fails

### ISSUE THREAD

**Issue by jkotan** [pni-libraries/python-pni#46]
On jessie I get

    ======================================================================
    FAIL: testBooleanArray (test.h5cpp_tests.attribute_tests.attribute_io_tests.AttributeIOTests)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/jkotan/sources/python-pni/test/h5cpp_tests/attribute_tests/attribute_io_tests.py", line 65, in testBooleanArray
	npt.assert_array_equal(a.read(),numpy.array(data))
      File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 718, in assert_array_equal
	verbose=verbose, header='Arrays are not equal')
      File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 644, in assert_array_compare
	raise AssertionError(msg)
    AssertionError: 
    Arrays are not equal

    (mismatch 75.0%)
     x: array([255,   0, 255,   0], dtype=uint8)
     y: array([ True, False, False,  True], dtype=bool)

    ----------------------------------------------------------------------

**Comment by jkotan** [comment]
the bug is related to https://github.com/ess-dmsc/h5cpp/issues/260

**Comment by eugenwintersberger** [comment]
This is a nasty bug which is hard if not impossible to fix. We will most probably not fix it in h5cpp because it is simply a HDF5 issue. There is an error in handling booleans in C-Apis prior to 1.10. Which leaves us with a rather unpleasant decision to make: either we invent our own boolean type and risk breaking the standard. Or we do it the standard way and support `native` booleans only as of 1.10. 
I have no idea what is the better solution.

**Comment by jkotan** [comment]
Is it possible to backport the 1.10 standard to 1.8, i.e. add  extension to H5CPP+1.8 from HDF5 1.10?

**Comment by zjttoefs** [comment]
Do we need to support 1.8 in the long run?

**Comment by jkotan** [comment]
From DESY point of view  we still use jessie (with 1.8) but I hope we can move to stretch (with 1.10) this year (this summer or end of the year). So the bug is not critical.

**Comment by eugenwintersberger** [comment]
It is actually I bit of a mess with all this special (non native C types). One could easily create a custom boolean type. But in this case this would be a special solution and 3rd party software may would not recognize this type automatically as a boolean. Another problem of this kind are complex numbers. There is a defacto standard created by PyTables and h5py but nobody stops you from deriving your own compound type for complex numbers.

**Comment by jkotan** [comment]
We have to remember that NEXUS/HDF5 files created by old API remains.  So they should be readable with use of new API.

**Comment by jkotan** [comment]
fixed in #67 and #66
