### ISSUE TITLE
RuntimeWarning: to-Python converter already registered; second conversion method ignored.

### ISSUE THREAD

**Issue by jkotan** [pni-libraries/python-pni#48]
It is not possible to use both `pninexus`  and `pni` packages together. When one tries to do it he/she gets the following error:

    In [1]: from pninexus import nexus

    In [2]:  import pni.io.nx.h5 as nx
    /usr/lib/python2.7/dist-packages/pni/io/nx/__init__.py:3: RuntimeWarning: to-Python converter for std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > already registered; second conversion method ignored.
      from ._nx import nxpath

or 

    In [1]: import pni.io.nx.h5 as nx

    In [2]: from pninexus import nexus
    /usr/lib/python2.7/dist-packages/pninexus/nexus/__init__.py:5: RuntimeWarning: to-Python converter for std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > already registered; second conversion method ignored.
      from ._nexus import is_nexus_file

**Comment by eugenwintersberger** [comment]
This is expected. And there is most probably no way how to deal with this.

**Comment by jkotan** [comment]
So do you mean it is a problem of `boost python` (so one has to use another bindings) or a problem of implementation of `python-pninexus` ?

**Comment by eugenwintersberger** [comment]
Well you can call it a problem of boost::python if you want. As a matter of fact it is a conflict in name resolution of the underlying shared object (if I understand the entire thing correctly). What is actually the use case to use both libraries together?

**Comment by jkotan** [comment]
Well, 

1) in the NXSDataWriter tango server I've got a factory where the user can changed a writer library dynamically. Currently, it works with `pni (old)` and  `h5py`.  I would like to add `pninexus`  as well but in the current state I cannot do it. That would me what every time the user change the writer library he/she has to restart the tang server.

2) i've been about to write compatilility tests, i.e. writing with one library and reading with other library. I've got them for `pni` <-> `h5py`.  It looks like I cannot do it with `pni` <-> `pninexus`, i.e. not in one python process which makes test more complicated.

3) it the first time I see two python packages you can installed work exclusively. 

If there are shared object, why it cannot be shared  between `pni` and `pninexus`? The `pni` and `h5py` uses the same `libhdf5` and it works OK. So either something is really wrong in `boost-python` or bindings of  `python-pni[nexus]`.

**Comment by jkotan** [comment]
Since  I'm not using to many interface of `pninexus.nexus` (i.e. `libpniio`) so in principle as a workaround I can use only `pninexus.h5cpp`which is free of this problem.

**Comment by jkotan** [comment]
The problem is caused by python boost static variable register storing  references to python boost types. In princple could solve the problem by adding the following check
```c++
boost::python::type_info info = boost::python::type_id<nexus::Path::Element>();
const boost::python::converter::registration* reg = boost::python::converter::registry::query(info);
if (reg == NULL || (*reg).m_to_python == NULL) {
```
but for Windows DLLs you would need to link python boost library statically to each DLL.

Since the old version of `pni` package is not used on debian10 anymore I close the ticket.
