### ISSUE TITLE
not supported unicode 

### ISSUE THREAD

**Issue by jkotan** [pni-libraries/python-pni#8]
Hi Eugen,

it seems that unicode is no more supported, i.e

```
import pni.io.nx.h5 as nexus

f = nexus.create_file("image_writer.nxs",True).root()

data = f.create_field("data","string",shape=(1,))
data[...] = u'dsgdgf'
```

gives

```
Traceback (most recent call last):
  File "fieldattr3.py", line 6, in <module>
    data[...] = u'dsgdgf'
TypeError: Exception: type_error


Description:
Type of numpy array cannot be handled!

Exception thrown by:
src/core/numpy_utils.cpp    98  pni::core::type_id_t numpy::type_id(const boost::python::api::object&)
```

Cheers,
Jan

**Comment by eugenwintersberger** [comment]
Have forgotten to test this for the 1.0.0 release - thus it can be considered a bug.

**Comment by jkotan** [comment]
For new API (v1.2.3) the following code works

    from pninexus import h5cpp
    from pninexus import nexus

    flag = h5cpp.file.AccessFlags.TRUNCATE

    fl = nexus.create_file("unicodetest.h5", flag)
    rt = fl.root()
    shape = [2, 2]
    dcpl = h5cpp.property.DatasetCreationList()
    dataspace = h5cpp.dataspace.Simple(
        tuple(shape),
        tuple([h5cpp.dataspace.UNLIMITED]*len(shape)))
    chunk = [2, 1]

    fdi = nexus.FieldFactory.create_chunked_(
        rt, h5cpp.Path("strimage"), h5cpp.datatype.kVariableString,
        dataspace, chunk, dcpl=dcpl)

    fds = nexus.FieldFactory.create(
        rt, "strscalar", "string")
    fdi.write([[u"as", u"asd"], [u"df",u"dfd"]])
    fds.write(u"as")
    print(fdi.read())
    print(fds.read())
    fl.close() 

So when we switch  from pni to pninexus  we can close the ticket.
